### ISSUE TITLE
get virtual service name 

### ISSUE THREAD

**Issue by daveRendon** [KEMPtechnologies/python-kemptech-api#2]
Not being able to get the virtual service name on methods: 

lm.get_all_objects()
lm.get_virtual_services()

**Comment by Dannyzen** [comment]
Thanks Dave. So that others who read this issue have full context why is a virtual service name important to your use case and what are you trying to do?

**Comment by daveRendon** [comment]
Got a customer request (datacenter) to list virtual services by name instead of IP´s to manage them easy... also looking into some similar requirements got this result: https://support.kemptechnologies.com/hc/en-us/community/posts/255466626-Virtual-Services

**Comment by lawnmowerlatte** [comment]
@daveRendon, since name is a malleable part of the VS, we store the name as an attribute of the VS object. That said you can easily craft your own VS dictionary with the names as the keys:

````
vs_by_name = {vs.nickname: vs for vs in lm.get_virtual_services() if vs.nickname is not None}
````

This example excludes unnamed VSs as they would otherwise come up as a single entry under the key `None`. You could work around that by injecting the socket information as the key if that was desired.

This is similar to how we create the `lm.vs` property which indexes on the VS index:
````
    @property
    def vs(self):
        return {int(vs.index): vs for vs in self.get_virtual_services()}
````

**Comment by Dannyzen** [comment]
Thanks @lawnmowerlatte. @daverendon this sounds like it answers your question. Please reopen this issue if you have any follow ups.
